In [1]:
import numpy as np

In [2]:
a = [1, 2, 3, 4]
b = [2, 3, 4, 5]

In [5]:
ab = [a[i] * b[i] for i in range(len(a))]

In [6]:
ab

[2, 6, 12, 20]

In [7]:
np_a = np.array(a)
np_b = np.array(b)

In [8]:
np_a * np_b

array([ 2,  6, 12, 20])

In [9]:
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [10]:
np.random.randint(0, 10, size=10)

array([5, 1, 3, 4, 2, 7, 7, 6, 5, 0])

In [11]:
np.random.normal(10, 4, (3, 4))

array([[ 7.8674079 , 10.74004672, 13.3514064 ,  4.46413283],
       [12.3857906 ,  9.72101707,  6.88554463,  9.16845848],
       [ 5.72118924, 11.65423593, 17.16071724,  7.01352593]])

In [12]:
a = np.random.randint(10, size=5)

In [13]:
a.ndim

1